### Insights Using Pandas

In [23]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv"
df = pd.read_csv(url)

df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [24]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [25]:
# 1) Quick overview
# df.head()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [26]:
# 2) Missing data
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [27]:
df.isna().mean().sort_values(ascending=False)

horsepower      0.015075
mpg             0.000000
cylinders       0.000000
displacement    0.000000
weight          0.000000
acceleration    0.000000
model_year      0.000000
origin          0.000000
name            0.000000
dtype: float64

In [30]:
# 3) Value distributions (category)
df["origin"].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [31]:
df["cylinders"].value_counts()

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [32]:
# 4) Group comparisons
df.groupby("origin")["mpg"].mean().sort_values(ascending=False)

origin
japan     30.450633
europe    27.891429
usa       20.083534
Name: mpg, dtype: float64

In [33]:
df.groupby("cylinders").agg(count=("mpg", "size"), avg_mpg=("mpg", "mean"))

           count    avg_mpg
cylinders
3              4  20.550000
4            204  29.286765
5              3  27.366667
6             84  19.985714
8            103  14.963107

In [35]:
# 5) Correlations
df.corr(numeric_only=True)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267
cylinders,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746
displacement,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164
horsepower,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361
weight,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564
acceleration,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137
model_year,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000

In [37]:
# 6) Top/bottom records
df.nlargest(5, "mpg")[["name", "mpg", "horsepower", "weight"]]

                     name   mpg  horsepower  weight
322             mazda glc  46.6        65.0    2110
329   honda civic 1500 gl  44.6        67.0    1850
325  vw rabbit c (diesel)  44.3        48.0    2085
394             vw pickup  44.0        52.0    2130
326    vw dasher (diesel)  43.4        48.0    2335

In [38]:
df.nsmallest(5, "mpg")[["name", "mpg", "horsepower", "weight"]]

               name   mpg  horsepower  weight
28         hi 1200d   9.0       193.0    4732
25        ford f250  10.0       215.0    4615
26        chevy c20  10.0       200.0    4376
27       dodge d200  11.0       210.0    4382
67  mercury marquis  11.0       208.0    4633

In [ ]:
# 7) Pivot table
pd.pivot_table(df, index="origin", columns="cylinders", values="mpg", aggfunc="mean")

cylinders      3          4          5          6          8
origin
europe       NaN  28.411111  27.366667  20.100000        NaN
japan      20.55  31.595652        NaN  23.883333        NaN
usa          NaN  27.840278        NaN  19.663514  14.963107

In [40]:
# 8) “Time series” style trend by model year
df.groupby("model_year")["mpg"].mean()

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

### Plots